//Author Gera Jahja
package src.interfaces;
import src.opcodes.*;


public interface Dissasemble 
{
    String visit(sh3 Sh3,int orderNo);
    String visit(add Add,int orderNo);
    String visit(stop Stop,int orderNo);
    String visit(mul Mul,int orderNo);
    String visit(sub Sub,int orderNo);
    String visit(div Div,int orderNo);
    String visit(sdiv Sdiv,int orderNo);
    String visit(mod Mod,int orderNo);
    String visit(smod Smod,int orderNo);
    String visit(addmod Addmod,int orderNo);
    String visit(mulmod Mulmod,int orderNo);
    String visit(exp Exp,int orderNo);
    String visit(signextend Signextend,int orderNo);
    String visit(lt Lt,int orderNo);
    String visit(gt GT,int orderNo);
    String visit(slt Slt,int orderNo);
    String visit(sgt Sgt,int orderNo);
    String visit(eq Eq,int orderNo);
    String visit(iszero Iszero,int orderNo);
    String visit(and And,int orderNo);
    String visit(or Or,int orderNo);
    String visit(xor Xor,int orderNo);
    String visit(not Not,int orderNo);
    String visit(bytee Bytee,int orderNo);
    String visit(shl Shl,int orderNo);
    String visit(shr Shr,int orderNo);
    String visit(sar Sar,int orderNo);
    String visit(address Address,int orderNo);
    String visit(balance Balance,int orderNo);
    String visit(origin Origin,int orderNo);
    String visit(caller Caller,int orderNo);
    String visit(callvalue Callvalue,int orderNo);
    String visit(calldataload Calldataload,int orderNo);
    String visit(calldatasize Calldatasize,int orderNo);
    String visit(calldatacopy Calldatacopy,int orderNo);
    String visit(codesize Codesize,int orderNo);
    String visit(codecopy Codecopy,int orderNo);
    String visit(gasprice Gasprice,int orderNo);
    String visit(extcodesize Extcodesize,int orderNo);
    String visit(extcodecopy Extcodecopy,int orderNo);
    String visit(returndatasize Returndatasize,int orderNo);
    String visit(returndatacopy Returndatacopy,int orderNo);
    String visit(extcodehash Extcodehash,int orderNo);
    String visit(blockhash Blockhash,int orderNo);
    String visit(coinbase Coinbase,int orderNo);
    String visit(timestamp Timestamp,int orderNo);
    String visit(number Number,int orderNo);
    String visit(difficulty Difficulty,int orderNo);
    String visit(gaslimit Gaslimit,int orderNo);
    String visit(chainid Chainid,int orderNo);
    String visit(selfbalance Selfbalance,int orderNo);
    String visit(basefee Basefee,int orderNo);
    String visit(pop Pop,int orderNo);
    String visit(mload Mload,int orderNo);
    String visit(mstore Mstore,int orderNo);
    String visit(mstore8 Mstore8,int orderNo);
    String visit(sload Sload,int orderNo);
    String visit(sstore Sstore,int orderNo);
    String visit(jump Jump,int orderNo);
    String visit(jumpi Jumpi,int orderNo);
    String visit(pc Pc,int orderNo);
    String visit(msize Msize,int orderNo);
    String visit(gas Gas,int orderNo);
    String visit(jumpdest Jumpdest,int orderNo);
    String visit(push Push,int orderNo);
    String visit(dup Dup,int orderNo);
    String visit(swap Swap,int orderNo);
    String visit(log Log,int orderNo);
    String visit(create Create,int orderNo);
    String visit(call Call,int orderNo);
    String visit(callcode Callcode,int orderNo);
    String visit(return_ Return_,int orderNo);
    String visit(delegatecall Delegatecall,int orderNo);
    String visit(create2 Create2,int orderNo);
    String visit(staticcall Staticcall,int orderNo);
    String visit(revert Revert,int orderNo);
    String visit(invalid invalid,int orderNo);
    String visit(selfdestruct Selfdestruct,int orderNo);

}